// AUTO-GENERATED by scripts/migrate-api-catchall.mjs — DO NOT EDIT
// brain/... 路由分发器：把 51 个原 route.ts 合并为 1 个 Serverless Function。
// URL 与行为保持不变；仅用于满足 Vercel Hobby 12 函数上限。
import { NextRequest, NextResponse } from "next/server";
import * as m0 from "@/lib/api-handlers/brain/active-brief";
import * as m1 from "@/lib/api-handlers/brain/ask";
import * as m2 from "@/lib/api-handlers/brain/curate/relation";
import * as m3 from "@/lib/api-handlers/brain/curate";
import * as m4 from "@/lib/api-handlers/brain/curate/similar";
import * as m5 from "@/lib/api-handlers/brain/curate/stale";
import * as m6 from "@/lib/api-handlers/brain/dashboard";
import * as m7 from "@/lib/api-handlers/brain/embedding/backfill";
import * as m8 from "@/lib/api-handlers/brain/ima";
import * as m9 from "@/lib/api-handlers/brain/ima/sync";
import * as m10 from "@/lib/api-handlers/brain/import/batch";
import * as m11 from "@/lib/api-handlers/brain/inbox/batch-process";
import * as m12 from "@/lib/api-handlers/brain/inbox";
import * as m13 from "@/lib/api-handlers/brain/inbox/[id]/process";
import * as m14 from "@/lib/api-handlers/brain/learning-reviews";
import * as m15 from "@/lib/api-handlers/brain/learning-reviews/[id]/action";
import * as m16 from "@/lib/api-handlers/brain/notes/decay";
import * as m17 from "@/lib/api-handlers/brain/notes";
import * as m18 from "@/lib/api-handlers/brain/notes/[id]/access";
import * as m19 from "@/lib/api-handlers/brain/notes/[id]/upgrade";
import * as m20 from "@/lib/api-handlers/brain/notes/[id]/versions";
import * as m21 from "@/lib/api-handlers/brain/notifications";
import * as m22 from "@/lib/api-handlers/brain/organize";
import * as m23 from "@/lib/api-handlers/brain/outcomes/[id]";
import * as m24 from "@/lib/api-handlers/brain/plans";
import * as m25 from "@/lib/api-handlers/brain/projects";
import * as m26 from "@/lib/api-handlers/brain/projects/[id]";
import * as m27 from "@/lib/api-handlers/brain/projects/[id]/workbench";
import * as m28 from "@/lib/api-handlers/brain/provenance";
import * as m29 from "@/lib/api-handlers/brain/reminder-settings";
import * as m30 from "@/lib/api-handlers/brain/reminders/read";
import * as m31 from "@/lib/api-handlers/brain/reminders";
import * as m32 from "@/lib/api-handlers/brain/report";
import * as m33 from "@/lib/api-handlers/brain/reviews";
import * as m34 from "@/lib/api-handlers/brain/snippets";
import * as m35 from "@/lib/api-handlers/brain/strategies/extract-from-analysis";
import * as m36 from "@/lib/api-handlers/brain/strategies";
import * as m37 from "@/lib/api-handlers/brain/table/analyze";
import * as m38 from "@/lib/api-handlers/brain/table/confirm";
import * as m39 from "@/lib/api-handlers/brain/table/confirm-columns";
import * as m40 from "@/lib/api-handlers/brain/table/export";
import * as m41 from "@/lib/api-handlers/brain/table/narrative";
import * as m42 from "@/lib/api-handlers/brain/table/upload";
import * as m43 from "@/lib/api-handlers/brain/tasks/extract-from-analysis";
import * as m44 from "@/lib/api-handlers/brain/tasks/gantt";
import * as m45 from "@/lib/api-handlers/brain/tasks";
import * as m46 from "@/lib/api-handlers/brain/tasks/[id]/comments";
import * as m47 from "@/lib/api-handlers/brain/tasks/[id]/detail";
import * as m48 from "@/lib/api-handlers/brain/tasks/[id]/outcomes";
import * as m49 from "@/lib/api-handlers/brain/weekly-review/plan";
import * as m50 from "@/lib/api-handlers/brain/weekly-review";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type HandlerFn = (req: NextRequest, ctx?: unknown) => Promise<Response> | Response;
type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
interface RouteDef {
  key: string;
  methods: Partial<Record<Method, HandlerFn>>;
}

const ROUTES: RouteDef[] = [
  { key: "active-brief", methods: { GET: m0.GET as HandlerFn, POST: m0.POST as HandlerFn } },
  { key: "ask", methods: { POST: m1.POST as HandlerFn } },
  { key: "curate/relation", methods: { POST: m2.POST as HandlerFn } },
  { key: "curate", methods: { GET: m3.GET as HandlerFn, POST: m3.POST as HandlerFn } },
  { key: "curate/similar", methods: { POST: m4.POST as HandlerFn } },
  { key: "curate/stale", methods: { POST: m5.POST as HandlerFn } },
  { key: "dashboard", methods: { GET: m6.GET as HandlerFn } },
  { key: "embedding/backfill", methods: { POST: m7.POST as HandlerFn } },
  { key: "ima", methods: { GET: m8.GET as HandlerFn, POST: m8.POST as HandlerFn } },
  { key: "ima/sync", methods: { POST: m9.POST as HandlerFn, GET: m9.GET as HandlerFn } },
  { key: "import/batch", methods: { POST: m10.POST as HandlerFn } },
  { key: "inbox/batch-process", methods: { POST: m11.POST as HandlerFn } },
  { key: "inbox", methods: { POST: m12.POST as HandlerFn, GET: m12.GET as HandlerFn } },
  { key: "inbox/[id]/process", methods: { POST: m13.POST as HandlerFn } },
  { key: "learning-reviews", methods: { GET: m14.GET as HandlerFn, POST: m14.POST as HandlerFn, DELETE: m14.DELETE as HandlerFn } },
  { key: "learning-reviews/[id]/action", methods: { POST: m15.POST as HandlerFn, GET: m15.GET as HandlerFn } },
  { key: "notes/decay", methods: { GET: m16.GET as HandlerFn, POST: m16.POST as HandlerFn } },
  { key: "notes", methods: { GET: m17.GET as HandlerFn, POST: m17.POST as HandlerFn, PUT: m17.PUT as HandlerFn, DELETE: m17.DELETE as HandlerFn } },
  { key: "notes/[id]/access", methods: { POST: m18.POST as HandlerFn } },
  { key: "notes/[id]/upgrade", methods: { POST: m19.POST as HandlerFn } },
  { key: "notes/[id]/versions", methods: { GET: m20.GET as HandlerFn } },
  { key: "notifications", methods: { GET: m21.GET as HandlerFn, POST: m21.POST as HandlerFn } },
  { key: "organize", methods: { POST: m22.POST as HandlerFn } },
  { key: "outcomes/[id]", methods: { PUT: m23.PUT as HandlerFn } },
  { key: "plans", methods: { GET: m24.GET as HandlerFn, POST: m24.POST as HandlerFn } },
  { key: "projects", methods: { GET: m25.GET as HandlerFn, POST: m25.POST as HandlerFn } },
  { key: "projects/[id]", methods: { PUT: m26.PUT as HandlerFn, DELETE: m26.DELETE as HandlerFn } },
  { key: "projects/[id]/workbench", methods: { GET: m27.GET as HandlerFn } },
  { key: "provenance", methods: { GET: m28.GET as HandlerFn } },
  { key: "reminder-settings", methods: { GET: m29.GET as HandlerFn, PUT: m29.PUT as HandlerFn } },
  { key: "reminders/read", methods: { POST: m30.POST as HandlerFn } },
  { key: "reminders", methods: { GET: m31.GET as HandlerFn } },
  { key: "report", methods: { GET: m32.GET as HandlerFn } },
  { key: "reviews", methods: { GET: m33.GET as HandlerFn, POST: m33.POST as HandlerFn } },
  { key: "snippets", methods: { GET: m34.GET as HandlerFn } },
  { key: "strategies/extract-from-analysis", methods: { POST: m35.POST as HandlerFn } },
  { key: "strategies", methods: { GET: m36.GET as HandlerFn, PUT: m36.PUT as HandlerFn, DELETE: m36.DELETE as HandlerFn } },
  { key: "table/analyze", methods: { POST: m37.POST as HandlerFn } },
  { key: "table/confirm", methods: { POST: m38.POST as HandlerFn } },
  { key: "table/confirm-columns", methods: { POST: m39.POST as HandlerFn } },
  { key: "table/export", methods: { POST: m40.POST as HandlerFn } },
  { key: "table/narrative", methods: { POST: m41.POST as HandlerFn } },
  { key: "table/upload", methods: { POST: m42.POST as HandlerFn } },
  { key: "tasks/extract-from-analysis", methods: { POST: m43.POST as HandlerFn } },
  { key: "tasks/gantt", methods: { GET: m44.GET as HandlerFn } },
  { key: "tasks", methods: { GET: m45.GET as HandlerFn, POST: m45.POST as HandlerFn, PUT: m45.PUT as HandlerFn, DELETE: m45.DELETE as HandlerFn } },
  { key: "tasks/[id]/comments", methods: { GET: m46.GET as HandlerFn, POST: m46.POST as HandlerFn } },
  { key: "tasks/[id]/detail", methods: { GET: m47.GET as HandlerFn } },
  { key: "tasks/[id]/outcomes", methods: { GET: m48.GET as HandlerFn, POST: m48.POST as HandlerFn } },
  { key: "weekly-review/plan", methods: { POST: m49.POST as HandlerFn } },
  { key: "weekly-review", methods: { GET: m50.GET as HandlerFn, POST: m50.POST as HandlerFn } },
];

/** 精确匹配优先，其次 [id] 动态段匹配；返回参数表 */
function matchRoute(path: string[]): { def: RouteDef; params: Record<string, string> } | null {
  const key = path.join("/");
  for (const def of ROUTES) {
    if (def.key === key) return { def, params: {} };
  }
  for (const def of ROUTES) {
    const parts = def.key.split("/");
    if (parts.length !== path.length) continue;
    const params: Record<string, string> = {};
    let ok = true;
    for (let i = 0; i < parts.length; i++) {
      const m = parts[i].match(/^\[([^\]]+)\]$/);
      if (m) params[m[1]] = decodeURIComponent(path[i]);
      else if (parts[i] !== path[i]) {
        ok = false;
        break;
      }
    }
    if (ok) return { def, params };
  }
  return null;
}

async function dispatch(
  method: Method,
  req: NextRequest,
  ctx: { params: Promise<{ path?: string[] }> },
): Promise<Response> {
  const { path: p } = await ctx.params;
  const hit = matchRoute(p ?? []);
  if (!hit) {
    return NextResponse.json({ error: "not_found", message: "接口不存在" }, { status: 404 });
  }
  const fn = hit.def.methods[method];
  if (!fn) {
    return NextResponse.json({ error: "method_not_allowed", message: "方法不支持" }, { status: 405 });
  }
  return fn(req, { params: Promise.resolve(hit.params) }) as Promise<Response>;
}

export const GET = (req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) => dispatch("GET", req, ctx);
export const POST = (req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) => dispatch("POST", req, ctx);
export const PUT = (req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) => dispatch("PUT", req, ctx);
export const PATCH = (req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) => dispatch("PATCH", req, ctx);
export const DELETE = (req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) => dispatch("DELETE", req, ctx);
