// AUTO-GENERATED by scripts/migrate-api-catchall.mjs — originkit genius/wexo 合并
import { NextRequest, NextResponse } from "next/server";
import { createStaticSiteHandler } from "@/lib/static-site-handler";
import { requireUser } from "@/lib/auth-guard";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const genius = createStaticSiteHandler("genius");
const wexo = createStaticSiteHandler("wexo");

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  // 整站模板（genius/wexo）仅供登录后的组件预览页 iframe 引用；
  // 此处补 handler 级鉴权，避免伪造/过期 auth cookie 绕过 proxy 门禁直读模板资源。
  const { res } = await requireUser();
  if (res) return res;

  const { path: raw } = await ctx.params;
  const path = raw ?? [];
  if (path[0] === "genius") return genius(req, { params: Promise.resolve({ path: path.slice(1) }) });
  if (path[0] === "wexo") return wexo(req, { params: Promise.resolve({ path: path.slice(1) }) });
  return NextResponse.json({ error: "not_found", message: "整站模板不存在" }, { status: 404 });
}
