// AUTO-GENERATED by scripts/migrate-api-catchall.mjs — originkit genius/wexo 合并
import { NextRequest, NextResponse } from "next/server";
import { createStaticSiteHandler } from "@/lib/static-site-handler";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const genius = createStaticSiteHandler("genius");
const wexo = createStaticSiteHandler("wexo");

export async function GET(req: NextRequest, ctx: { params: Promise<{ path?: string[] }> }) {
  const { path: raw } = await ctx.params;
  const path = raw ?? [];
  if (path[0] === "genius") return genius(req, { params: Promise.resolve({ path: path.slice(1) }) });
  if (path[0] === "wexo") return wexo(req, { params: Promise.resolve({ path: path.slice(1) }) });
  return NextResponse.json({ error: "not_found", message: "整站模板不存在" }, { status: 404 });
}
